on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle compile
        run: ./gradlew compileKotlin

      - name: Execute Gradle test
        run: ./gradlew test

      - name: Build docker image
        run: |
          ./gradlew jib \
              -Djib.to.image=ghcr.io/${{ github.repository }}:latest \
              -Djib.to.auth.username=${{ github.actor }} \
              -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}